---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-slack
  namespace: monitoring
spec:
  encryptedData:
    webhook: AgBfWgAf5zxJxDEucCyg48RKQQ+a3Xy5QODiiJfRs1uPeUSo6oOwD/RWhEXONIJtBRAVf8VZcQpYj29Ucmm9Fl3i5iiJNgvn13bIWobwdMphESbRujjLTTDzgZoild6q8XrT/tCy+YeCV1GhfM4VVWDubfRybVvUT7Cf6YlGJx3+Mk+ZkylNz4vvVmvNJEXG31wt1eBYGlvP100CAot+VMYKBCC9RH8/oMV1tMYT8MdiyImqwUiJM1sYtZBhRWTPWesvA3EMC7YInhIbpKPEzfz0m6JvZArjv0U95kUY/+Ve5uaoj0ajfDH66lDPkcq2o32ieimKemjWFGyKK4rFO9riZ9GfnYMJVur8QRQ5q8QziR0FCTMYUttmCJEzAqxEkY833/779j6frbqwY2hUprKbFNR3u/Loeu5TkfpYZYjaWfNsYgg23TcYLRzux10rYE7oasMSk4+YXmREuinV9i1qcgDs/HlU0SAIDPkZHXuhA22OlhEaVwanDdxFItckTiVtxS/x5DzQjMeud5sUDx7mh+vwJGjSaLSkvuQJKtERw9bympQcPAHOLcc+lUMKODAZEbrAg3wxT1fLA8U8t9N+vUBlernCb/7P7iySJUFuk26bQq3znAsQZBH03BXFbRcN1RkgU3m0Pcp7gdqYtL1rPKELtxKIMCL9kC+F0ar/OZcrhlwU+HDuxJMGb9vqXPxlP/b4YqrbVSAcRsOVQGeTNIxfnVN7hHTPVqOjIBKxO/h77M+MXFNQPEdtSj/v7oaMQKAGulG4vE2SUWK/Avtle39+Vc0pqCJ69C7Yni6toig=
  template:
    metadata:
      creationTimestamp: null
      name: alertmanager-slack
      namespace: monitoring
    type: Opaque
