---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-slack
  namespace: monitoring
spec:
  encryptedData:
    webhook: AgB5YuNtHQ2GZe0UB486Vd76aK/OUNSKptIEzrtLhq67pEgb8z03fKf9bYHYs46l5zQqRoI5qRTFE4IwT9x7riWMTR6hLLOtkyc+VPkBoLcb/uboYfDdXl0ZrRphsQC2uL3Ru1tbsEXVtakeeCrSjNFDT8JlUkIF19CKwPqyaTmqdjKqYLiTdA6tnet5D5lGQ4dtwJRh+jZ3yxC74LVJPXoEKg08+DLErxvYQ7MEJD2IJamcg7fRC5s+/76Y+IGhfyD+uGe8juGDVUbA/VX1sXySNRXZsW1MpYL2tI2+GxCMVRZXoYIqQ3wnAoLLJ2UDj51FlL2Yl/XcuG87QM5FJS37KaDXqQ2oHx9oHfiPX858fcIQ4CoNtr9zuaPXattrlxJGIDlA495wH4xuZdImQEaW6l8A+NbcCshhn6rLz231lD9w8AKuiy3TuoIU09LHFtnW/aZ786GD8U5gpGXJSjy/8t4zHw2JgTehS4O8vEkNqG6Hs5JEBkJgQhRNJJrEwbTZ9sPmfiq+63muibxkCE1VSnrYelh4imnyh0iw6C/r25d0TjO6bfTRuZykkKmVqOdQCEjEM2JllPlEXmeGBqNm2Ra4AwE/h25VFYsmGG2UC6BLewigsgVTsCyLcjGacfgbb4s8kI2PvSI1rw3IgMZPzFyNlzfCFEQx895myvqXhzD8lOhGeVerVjmLzfjwMbCM33AyXJHGkjlA3bIZkMjIU1/dhdfGy7McxRiQHr7L1HuQ1awLNXykYhtRgfkoBZbB5/oOJfSZQF4ASCbwdwT5E+Oxw+yHhANw2o1mEXVr5Bs=
  template:
    metadata:
      creationTimestamp: null
      name: alertmanager-slack
      namespace: monitoring
    type: Opaque
