---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-slack
  namespace: monitoring
spec:
  encryptedData:
    webhook: AgC350HOWDyua35Kn4T66uNR3cw2IheHs/mDu6Z8eKXQC4lHUScwGQlUy2Sy/D9DBnbH/KTa+r9YPd6BHjJEfTcq4sDFfbWEFHdVtoKU8CCgxRzFW4q5L3KFzz3k2O86BNO5LWCVqxzwl+iIomO56Zd3+8Y11ICMNNrpERNZAamOPHK4pWKfD3wLfCs1mBhXX04DO4K8tbsMh5BIgZxXUWIy5BZhNcacAQzw4ujJnunaUBxRgNrJm3Ri5BCVuLXZv4RXIDzWabufjJuFcXGpt5RLbwGiuWJtlWOx/SZ8fJCRYrCjM1Rleoi1MncoOx8IUNQY0MkSW1tYpKzhTLKrkWjsHEZuJUfTz6I6rAcTiOMrgIOTzW+GZNDmuYtfYpsDhDihh3zk1PQqkohCZk19DNT2vwZ5aeIaQA3j+yIkRWoyd/KxM9g5iKBHWvKPAH1NdnzKU8A8VrF9JEWjt0KJ/Gq9Fmea7ANIHoglZNCQzA/1SSTchfFzZZMsJWoftyRMNQw+IyU+mViKt5DFo2xOVeXXtt3KC54gHgWSIrpYZ28jEaeaWnofmiN+WzZPxYOOACzSuhZ3qfoX/CHIXczJYPJuqDGbQQwn/l1hsiVMlwP3ESTs2JR9FoqmjeH60zskbIHqzaLGaF6kMjjYuuOZOMNAkPeMINastJAbo9USpn3D0WGZ4f5qDDRNHVppJz0XT1OpNBg5AAYvCyGPmDVxkGj/0H199VSDMlroCgUkpS9JTCqAzX53Bw/vF6SBgPqEE4bsUK+r78HQuQoivIrfBYjw+jp87O4zEQhRCFsCL6bfR+I=
  template:
    metadata:
      creationTimestamp: null
      name: alertmanager-slack
      namespace: monitoring
    type: Opaque
