---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gateway-secret
  namespace: mlops
spec:
  encryptedData:
    GATEWAY_API_KEY: AgCbQAJZ9Z9D9muDgehZqSCEAdZNZPaE7J9nYVFHVUnf33p5irhuTXrlTiAxyy4+hEyJwv9OKaemPRultAEPeY/pZMgqKR5ANRykq/pnJxTT6UymwR8oVLhuvced1KXr5ifJWEROnFoLDH2ArS3hAWCxdd1TmsBUc9FCvcn3+OCiJg4Fvu9uC7YzsCn6PuhCHE1Bx7s4CALUeMaoKA3ivN1+bPBvKdqJkCbL+HRoJc0C2bn1l8oMUBUf5MeT+hYG370E5b5YN2jNgil/scfkoOPlx7E3qfNvYqVTXrIqHj3vbiuuY6Doof+j2e3lFGtm9lDb12AybolX9ytiR8tpuPeI7LB0M4k8UcLkfnn1+pwIMzIefwdaC4xZPcaY4QGYVcy3XubBG3HqS6w5qO6Yda0pNFXXp+Cwrx00pwQrhmBIBovwHj9Z0kJA3NZHBSKyJz0tJlfV5dju2+ksEcQ/H9spISDY0EroHhP+su4uyhYCKNKwiqMRkIWzHnYa+bkokm/b+WqSDoLKFbnn3hlImygo15lkjnFK7hVnArlCNK6HzbSlXyA0kc/+UMkGComY8Sogjsv1j28v/pU1aWFl24v7xqkKCRGyI0JoZye12HXeap+8PKUIfnJRWIJWgdcIswbNpprj42YrYX0wIInE+pNqUZBD5vYaKpWnuLtbIMH6KHSKXtTOwGVsMc8kM5p2rbzo3wMFG1gY
  template:
    metadata:
      creationTimestamp: null
      name: gateway-secret
      namespace: mlops
    type: Opaque
