---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gateway-secret
  namespace: mlops
spec:
  encryptedData:
    GATEWAY_API_KEY: AgA3n7dW2+qQml5sL1BsnY5DC3cvBkDGAfcLOXpdhzAvrnX8WUY0XsO0MLByVBB62XiPhGje4XY1xn2P+lEVkJc9H2M0yJhtPOikEziFhSTo+iUaMdigD3ddkiFGBYrgIC74V+cI+T0AC+o4/lzYv42l3rhbP2hL4/lxOMOFw1DoFAi2kdJTdLFeG7O0P0ADSIb8ILdjNiAwAU8hNCesjzf7bNRn3CfEgJcrJk+8Ggm9dQ1LbdfOn6h0w8w/WQd+gUSOBlGsSQQQIWFJ28PH+nEFuyl0cTZUQD3cvWem1qHfDXex3D2SumQd/oXLXMLhXNLCdLFXAAcSQEHZGDA5Mntick5RjRDIKQepuUUu3SUfMfJGBn/X8B5DZ6wrVTjWXzJyhTbzPHvVYl4drQvJA5ey4oR35UzJ7xTDOds0I37u/4708n8uWkIaCrg51SuCt/w6L5I+PQAGo+S4+3brtLtHK45OYTmSeRHNadbp/6o0nMwb34CypnrZu1E/yoXCJLvkI6RhOjh0fJEEV+/ijj/W+UDu1m6JrGSe20qS4YtlbeTVQdVZpjGkGswWnfY+vPCMEMolSeVWcHdLtcq8UOuZwS9DECuGlUi3PubSeLjWUFjV1wS2L1H80U7qkl58NyQp73+rWm9UH9i7uytscIwZ2QP31tYQc8dKWUf7XJRQaaVr9Rmkkpaq9d1Cd1k1oKOkBBQrtpx2
  template:
    metadata:
      creationTimestamp: null
      name: gateway-secret
      namespace: mlops
    type: Opaque
