---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gateway-secret
  namespace: mlops
spec:
  encryptedData:
    GATEWAY_API_KEY: AgAW1ca6LeTEbKG3fseEv5eRYhIXGHe6LzZnf4iDCcbG23DpMCepkTxP3K4/VEWpcZqgqEvVp/Hsn6eEiOxfv+VdxP2bAcwg6MrBIwNah3fkgSCy78rR3Bl1JK8ZgUKyOQ87g1xhdVcz05J+Wwcd7+n4AxE2txmDNe2bc8R1eiYkF4D81Q+TfTtcVa4Q+wB+ympihczpgPJdy+oURZyMEV0v4FKEha0Kvu41vS00MLpMsChcxHNf2X8HLea2c084Mlh79Grq1dxCjRiCVKBUHzWdaKQMQfKqkTUnS8BOXfElGrWH5GN+eeAfzmzLuW0TdwXjDDrxsvzEG73nMNf56LCPjMtd519W+kVKJdCGWEFHHfVJ1uUwsU2RlkHN1FTzKkKg+K7ThQy+1c+0ADMKPC5BMeCu6QwrBEsM/WUhx89Q5LXmG+tm0bh8fUKrojwbGx0833yYs+yUEIR0WqK1P434b4Mo0s3Ohn4hY3f9gTzPFvlSDmDpN+t9y5+YBp+Lz9roZPdxoNP2zbF0HjrcJxkqgf/Vhvp2rVWslAzVX0bNsg7doVbWZ3JK/RlQZOyk2LjuQBr0pRvKQre3cg57NyeNLatHm/GuL47qzAI4C2SEH3+jM9uTs5OO62I1sTCU2LM/9+eSJBqFZwcSLQkHHctJJLMeB0b68FUIGeoeclcSai89G86GnUnd2qEdX+y9aOfbHHjscSu/
  template:
    metadata:
      creationTimestamp: null
      name: gateway-secret
      namespace: mlops
    type: Opaque
