---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: model-secret
  namespace: mlops
spec:
  encryptedData:
    HF_TOKEN: AgBzmzt4vxEMz+9HG9/luc9MNIsNlKIX3VNgGHaSx7Cl+xjBGqVjS3vgPe4X5hr05oi7vd/vTk9Pm2WCLq05ZYJEwQd+wKsFfisCGIWEM3/eAyx/+j5FEMrrHVKXt8QBGaDlo6qowGZzIN6Osq06N4VetLIxdTEkln3LPY2J2FQxtkRK8wq/mRP7qVYiMFIV4kUjcK/ylUWTgbXMvgstd2yHcT8FdxadWo7/kMR3z7HSBE1n4R0hWp3MjzlU2jioRoa7/2rxxscJZLYAqUr4IfCz6vBkIOZZpfU8TgrUbZFg5NsDoxxq2WEyDZL7nalz1a7IjE8vthdaRHfwy20q4vw4gxgeIJkTovmHqHx04xcMqPGVJgy8DKtAiSWAGvrOpwfKBTTFSm52rGYHbMD7xHWNqQ9CGVkGOIkI8eDaYJn5YLi5tnAALgsV9IUE1FoMwZyi9uThwsIk/3ZT3NDNeet00JZ/lfSuz1okfKDZ/DZ9Tn6Gd0USFBAaLcKYCGyJEhxwGDlq7XAhOApuCLZaN4id71DAlKHBU4f8Bamqd+IzpHCKO6J9B/qMvqud23rKP5FrB5Qid0L1QDZLupOBxZdpCWjGu7f3M6b/aftwkUUJlIMMXZ64obMwDw16vImIUZ3ToMn1s/WD8H/FoBC5rwxg3+piba/S6eJv1mLCOZkZkqJ0qDOFuQhikjf3mO1nZBEcflNvEcf2RgBB+3j8a/zpjgwin1FCBIdgJc+HYDI7/HPVa28X
  template:
    metadata:
      creationTimestamp: null
      name: model-secret
      namespace: mlops
    type: Opaque
