---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: model-secret
  namespace: mlops
spec:
  encryptedData:
    HF_TOKEN: AgA+v+sOSegbu36ijY3naIy36Of6KeP7HDsJggfh/KUaK72LDlBikqKQtXUwDbheyVR+yY+LlYdHAKCwNyl5cKk/c1QClTSHktrjx+7JjuEWaAZ+/U7fBg0D9+8J8iapZTjFD0FKaCoLzdQhaX1cDHbD2Ok8OtV87UXuMDjrIoixECq7hBoV6fhn9I6PWNrmRFVdq4V9pL9h/zWxu9iuIraOTQOYtoxKt08Pf9gU27cnKkqMdMfc+d9KvT6ULOKzM1V2K57MIl6IV0NvRI5difwBB/XiVSSiN6gRRywS3amnaVxQ3NLrzUk7pUl8cWCV0tIwXr1BLG4eQKugLrgY93baTb2sSSb5Kq7PmVxoeSJ3z/o4H3pk1/UxIjycw3A5ddzNeKcCaDxkR0qsFnTG2CPYh187p/bZ4hWYXqhlolVmx0yYLb8hOVY9Hx/TneW5P2BgSppBBOTs3nD2ZBIGF7m4//C8alKrXUQhYogykAG9It52xocKEABoF1xYdcCCUMTtV/tvxX0CfPHbwlejGB/pSH/VjPnwuj2+CWqAdH9eNDTRmT47+gC4xNAiW4FqdP9DN8xJF8WkiH6DmboIBf9aLoC3via+E+lUXEIrqX4nUNDYxTLw4LomnvBi2NLwWwg+iVBdFeXU/G+LTqsQikVXH56mmGaVCIVDU2IKtM2UPlP8V9xsH8SEbOSZCyGMPNfb6NKt7Vhgi/ykF+1+S+t2VkELgebZEDdZnZquRk6K4xqNCt9n
  template:
    metadata:
      creationTimestamp: null
      name: model-secret
      namespace: mlops
    type: Opaque
