---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: model-secret
  namespace: mlops
spec:
  encryptedData:
    HF_TOKEN: AgCKZ87XzCJfIAopfuBlCQzzLBg7tm5AqZwz1b1Sqk61DvwOb+BoITFTOHK3DvfmMvUQIpUG4ad4DsGqTAjhApYHD5nuHdFlXNL3ATEsUipg8UocvzpBgckMNHGbuktwcFV+dq6B2sE0OC6wuyjf7YsN5cJmURVDfQ0nv50kf0B57ouz5F9fRXwyf92RU7otn9wyFdI1K2AirK49HlcwKpRJtjFXsNXAIG9uGIOCJk88fuNtZdtS1uAhU9suax2OdnyfCzSnE36auidaeJyiATxl02naWgyoOQdU15ZNPDVK+0Da+gBV8xtXa87nK/3yZSU6mIYX9EPtvIUgkmAPfm/Mk5T9g10S/yH6sYty+z03iI+rf7DC/1SsAJyflMuubuzgBsMO4pwssrIodml+pKO7v+gcUSPXGSFjJRwehuq/q55JXIxRxdFVwe6xZCuyqvsGKDDKH7m9F5gnlnoCztTZ+K96ljDQ9SBGbcJnoYamlxf/E2u0yfV3cFuOULJAd6e53sej3FYiq2PthZHQ1qNOFRZsP9X98KTQSZJGRTtP9p5pQg3Pzpud6qOhouAjyjR2JpoFSNGgfE1eqlK8/p6MOoLxqWFrbaMjKrckYz8Xr+yDPOB0W4S3aplyevdybe5VqvuUpiqrdvVB6ywpC7U+sDm/T4mPlBUyfuXfVJRjQd2k9dRo1b40F/v6/NLPDlCPwLoUa1U+cac6/UIs8B3Xhv+KNGuNnhtvV+0O8DnKvBTv0Nx/
  template:
    metadata:
      creationTimestamp: null
      name: model-secret
      namespace: mlops
    type: Opaque
