apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mlops

images:
  - name: vin1989/finbot-agent
    newTag: git-5230a026fd4b

resources:
  - rbac.yaml
  - deployment.yaml
  - service.yaml
  - servicemonitor.yaml
